name: boost

services:
  db:
    container_name: boost-db
    image: mysql:latest
    networks:
      - net
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: unless-stopped
    # healthcheck:
    #   test:
    #     - CMD
    #     - mysqladmin
    #     - ping
    #     - '-p${DB_PASSWORD}'
    #   retries: 3
    #   timeout: 5s

  ws:
    container_name: boost-ws
    image: boost/build
    build:
      context: .
      target: build
    pull_policy: build
    networks:
      - net
    ports:
      - 8085:80
      # db:
      #   condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    init: true
    restart: unless-stopped
    # post_start:
    #   - command: php artisan optimize:clear
    #     user: ubuntu
    # pre_stop:
    #   - command: php artisan optimize:clear
    #     user: ubuntu
    develop:
      watch:
        - path: .
          include:
            - composer.json
            - package.json
            - public
            - resources
          action: rebuild
        - path: .
          target: /var/www/html
          include:
            - app
            - bootstrap
            - config
            - routes
            - .env.local
            # - views
          action: sync+restart
          initial_sync: true

  dev:
    container_name: boost-dev
    profiles: [ dev ]
    image: boost/dev
    build:
      context: .
      target: dev
    pull_policy: build
    networks:
      - net
    ports:
      - 8086:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: .
        target: /var/www/html
      - logs:/logs_ws
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    init: true
    # post_start:
    #   - command: chown -R ubuntu:www-data storage bootstrap/cache
    #     working_dir: /var/www/html
    #     user: root

networks:
  net:
    driver: bridge

volumes:
  db-data:
  logs:
